### PR TITLE
 [Refactor] update of the group card border color

### PR DESCRIPTION
**Pull request by NOUMA-03**
small update of the group card's border's color

### CODE REVIEW

**Review by YoussefACHCHIRAJ — APPROVED** [review]
bad

**Comment by YoussefACHCHIRAJ** [comment]
make a clean commit message which follow our conventions.

**Comment by NOUMA-03** [comment]
> make a clean commit message which follow our conventions.

What r ur conventions?

**Review by YoussefACHCHIRAJ — APPROVED** [review]
jiu

**Pull request merged**
